name: Build and deploy to GitHub Pages

permissions:
  contents: write

on:
  push:
    branches: ["main"]
  # Allows manually running from Actions tab
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          ref: 'archive'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: interface      # Specify the folder containing the static website files
          
